export { default as MushRoomProfile } from "./Mushroom.png"
export { default as CarrotProfile } from "./carrot.png"
export { default as OnionProfile } from "./onion.png"
export { default as BroccoliProfile } from "./broccoli.png"
export { default as SweatEmoji } from "./sweatEmoji.png"
export { default as YawnEmoji } from "./yawnEmoji.png"
export { default as CheckEmoji } from "./checkEmoji.png"
export { default as SunglassEmoji } from "./sunglassEmoji.png"